CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_provider VARCHAR,
    provider_user_id VARCHAR,
    nickname VARCHAR NOT NULL,
    profile_image_url VARCHAR,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_users_auth_provider_user UNIQUE (auth_provider, provider_user_id)
);

CREATE TABLE chat_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_a_id BIGINT NOT NULL,
    user_b_id BIGINT NOT NULL,
    relationship_started_on DATE,
    room_status VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    CONSTRAINT fk_chat_rooms_user_a FOREIGN KEY (user_a_id) REFERENCES users (id),
    CONSTRAINT fk_chat_rooms_user_b FOREIGN KEY (user_b_id) REFERENCES users (id),
    CONSTRAINT ck_chat_rooms_user_order CHECK (user_a_id < user_b_id),
    CONSTRAINT ck_chat_rooms_status CHECK (room_status IN ('ACTIVE', 'ENDED')),
    CONSTRAINT uq_chat_rooms_user_pair UNIQUE (user_a_id, user_b_id)
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    client_message_id VARCHAR NOT NULL,
    content TEXT NOT NULL,
    sent_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_messages_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms (id),
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id),
    CONSTRAINT uq_messages_sender_client_message UNIQUE (sender_id, client_message_id)
);

CREATE INDEX idx_messages_chat_room_sent_at ON messages (chat_room_id, sent_at);
CREATE INDEX idx_messages_chat_room_id ON messages (chat_room_id, id);

CREATE TABLE ai_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_request_id UUID NOT NULL,
    chat_room_id BIGINT NOT NULL,
    recipient_user_id BIGINT,
    result_type VARCHAR NOT NULL,
    visibility_type VARCHAR NOT NULL,
    content_type VARCHAR NOT NULL,
    trigger_message_ids JSONB NOT NULL,
    result_data JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_ai_results_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms (id),
    CONSTRAINT fk_ai_results_recipient FOREIGN KEY (recipient_user_id) REFERENCES users (id),
    CONSTRAINT ck_ai_results_result_type CHECK (
        result_type IN ('TONE_CORRECTION', 'DATE_RECOMMENDATION', 'YOUTUBE_RECOMMENDATION')
    ),
    CONSTRAINT ck_ai_results_visibility_type CHECK (visibility_type IN ('INDIVIDUAL', 'COUPLE')),
    CONSTRAINT ck_ai_results_content_type CHECK (content_type IN ('TEXT', 'LINK', 'MIXED')),
    CONSTRAINT ck_ai_results_recipient_by_visibility CHECK (
        (visibility_type = 'INDIVIDUAL' AND recipient_user_id IS NOT NULL)
        OR (visibility_type = 'COUPLE' AND recipient_user_id IS NULL)
    )
);

CREATE INDEX idx_ai_results_analysis_request ON ai_results (analysis_request_id);
CREATE INDEX idx_ai_results_chat_room_created_at ON ai_results (chat_room_id, created_at);
CREATE INDEX idx_ai_results_recipient_created_at ON ai_results (recipient_user_id, created_at);
CREATE INDEX idx_ai_results_trigger_message_ids_gin ON ai_results USING GIN (trigger_message_ids);
