CREATE TABLE emotion_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_request_id UUID NOT NULL,
    chat_room_id BIGINT NOT NULL,
    subject_user_id BIGINT NOT NULL,
    viewer_user_id BIGINT NOT NULL,
    emotion_type VARCHAR NOT NULL,
    intensity_value NUMERIC NOT NULL,
    should_show BOOLEAN NOT NULL,
    trigger_message_ids JSONB NOT NULL,
    state_text VARCHAR,
    detected_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_emotion_analyses_chat_room FOREIGN KEY (chat_room_id) REFERENCES chat_rooms (id),
    CONSTRAINT fk_emotion_analyses_subject FOREIGN KEY (subject_user_id) REFERENCES users (id),
    CONSTRAINT fk_emotion_analyses_viewer FOREIGN KEY (viewer_user_id) REFERENCES users (id),
    CONSTRAINT ck_emotion_analyses_emotion_type CHECK (
        emotion_type IN ('STABLE', 'RESOLVED', 'ACCUMULATED', 'ENGAGED', 'ESCALATED')
    ),
    CONSTRAINT ck_emotion_analyses_intensity CHECK (intensity_value BETWEEN 0.0 AND 5.0),
    CONSTRAINT ck_emotion_analyses_distinct_users CHECK (subject_user_id <> viewer_user_id)
);

CREATE INDEX idx_emotion_analyses_analysis_request ON emotion_analyses (analysis_request_id);
CREATE INDEX idx_emotion_analyses_chat_room_detected_at ON emotion_analyses (chat_room_id, detected_at);
CREATE INDEX idx_emotion_analyses_subject_detected_at ON emotion_analyses (subject_user_id, detected_at);
CREATE INDEX idx_emotion_analyses_viewer_detected_at ON emotion_analyses (viewer_user_id, detected_at);
